spring:
  thymeleaf:
    cache=false
    prefix=file:src/main/resources/templates/

  datasource:
    generate-unique-name: false
    name: pizzacloud

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ##
            clientSecret: ##
            scope: ##
            #redirect-uri: ##